#!/usr/bin/env bash

# Display help usage
function usage() {
cat <<EOM
Usage: ${0} [OPTION]

Options:
  -c, --config      Display current fan configuration
  -i, --install     Install the Argon ONE Case Fan / Argon FanHAT driver
  -u, --uninstall   Uninstall the Argon ONE Case Fan / Argon FanHAT driver
  -h, --help        Display this usage information
EOM
}

function config_argonone() {
    if [[ -f "${daemonconfigfile}" ]]; then
      echo "Current Argon fan configuration:"
      echo
      cat "${daemonconfigfile}"
    else
      echo "${daemonconfigfile} not present. Default settings will be used."
      echo "55=10"
      echo "60=55"
      echo "65=100"
    fi
    echo
    echo "Edit ${daemonconfigfile} to change your fan curve and then run"
    echo "sudo 'systemctl restart argononed.service' to activate the changes."
}

function install_argonone() {
    apt install -y python3-rpi.gpio python3-smbus i2c-tools

    if [[ ! -f "${daemonconfigfile}" ]]; then
        # Generate config file for fan speed
        cat <<'EOM' >"${daemonconfigfile}"
#
# Argon One Fan Configuration
#
# List below the temperature (Celsius) and fan speed (in percent) pairs
# Use the following form:
# min.temperature=speed
#
# Defaults; 10% fan speed when >= 55C, 55% fan speed when >= 60C, 100% fan speed when >= 65C
# 55=10
# 60=55
# 65=100
#
# Always on example, fan will always run at 100%
# 1=100
#
# Type the following at the command line for changes to take effect:
# sudo systemctl restart argononed.service
#
# Start below:
55=10
60=55
65=100
EOM
        chmod 644 "${daemonconfigfile}"
    fi

    # Generate script that runs every shutdown event
    cat <<'EOM' >"${shutdownscript}"
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# -*- mode: Python; tab-width: 4; indent-tabs-mode: nil; -*-
# PEP 8, PEP 263.
"""
Argon One Fan and Button Service Daemon
"""

import smbus
# import RPi.GPIO as GPIO
from gpiozero import Button
from signal import pause
import os
import time
from threading import Thread
import logging

logging.basicConfig(
    format="%(asctime)s %(levelname)s - %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
    level=logging.INFO)
log = logging.getLogger("argonone")
log.setLevel(logging.INFO)

check_interval = 10
#rev = GPIO.RPI_REVISION
#if rev == 2 or rev == 3:
#    bus = smbus.SMBus(1)
#else:
#    bus = smbus.SMBus(0)
bus = smbus.SMBus(1)

#GPIO.setwarnings(False)
#GPIO.setmode(GPIO.BCM)
button_pin = 4
#GPIO.setup(shutdown_pin, GPIO.IN, pull_up_down=GPIO.PUD_DOWN)
button = Button(button_pin, pull_up=False)

max_fan_mode = False

# shutdown_button_press_time = 0

def button_pressed():
#     global shutdown_button_press_time
#     shutdown_button_press_time = time.time()
    global max_fan_mode
    max_fan_mode = not max_fan_mode
    log.info(f"Button is pressed, max fan mode is {max_fan_mode}.")

# def button_released():
#     global shutdown_button_press_time
#     if shutdown_button_press_time == 0:
#         log.error("The button is not pressed but released, weird...")
#         return
#
#     held_duration = time.time() - shutdown_button_press_time
#     log.info(f"The button was pressed and held for {held_duration:.2f} seconds.")
#
#     if held_duration >= 2 and held_duration <= 3:
#         log.info("Reboot...")
#         os.system("reboot")
#     elif held_duration >= 4 and held_duration <= 5:
#         loging.info("Shutdown...")
#         os.system("shutdown now -h")
#
#     shutdown_button_press_time = 0

def button_check():
    button.when_pressed = button_pressed
    # shutdown_button.when_released = shutdown_button_released

    pause()
    # while True:
    #     pulsetime = 1
    #     GPIO.wait_for_edge(shutdown_pin, GPIO.RISING)
    #     time.sleep(0.01)
    #     while GPIO.input(shutdown_pin) == GPIO.HIGH:
    #         time.sleep(0.01)
    #         pulsetime += 1
    #     if pulsetime >= 2 and pulsetime <= 3:
    #         # TODO: Use subprocess instead of os.system
    #         os.system("reboot")
    #     elif pulsetime >= 4 and pulsetime <= 5:
    #         # TODO: Use subprocess instead of os.system
    #         os.system("shutdown now -h")


def get_fanspeed(tempval, configlist):
    for curconfig in configlist:
        curpair = curconfig.split("=")
        tempcfg = float(curpair[0])
        fancfg = int(float(curpair[1]))
        if tempval >= tempcfg:
            return fancfg
    return 0


def load_config(fname):
    newconfig = []
    try:
        with open(fname, "r") as fp:
            for curline in fp:
                if not curline:
                    continue
                tmpline = curline.strip()
                if not tmpline:
                    continue
                # FIXME: Use startswith here
                if tmpline[0] == "#":
                    continue
                tmppair = tmpline.split("=")
                if len(tmppair) != 2:
                    continue
                tempval = 0
                fanval = 0
                try:
                    tempval = float(tmppair[0])
                    if tempval < 0 or tempval > 100:
                        continue
                except:
                    continue
                try:
                    fanval = int(float(tmppair[1]))
                    if fanval < 0 or fanval > 100:
                        continue
                except:
                    continue
                newconfig.append("{:5.1f}={}".format(tempval, fanval))
        if len(newconfig) > 0:
            newconfig.sort(reverse=True)
    except:
        return []
    return newconfig


def temp_check():
    fanconfig = ["65=100", "60=55", "55=10"]
    tmpconfig = load_config("/etc/argononed.conf")
    if len(tmpconfig) > 0:
        fanconfig = tmpconfig
    address = 0x1a
    prevblock = 0
    while True:
        with open("/sys/class/thermal/thermal_zone0/temp", "r") as fp:
            temp = fp.read()
        val = float(int(temp)/1000)
        log.info(f"CPU temperature: {val}")
        block = get_fanspeed(val, fanconfig)
        if max_fan_mode:
            block = 100
        if block < prevblock:
            time.sleep(check_interval)
        prevblock = block
        try:
            bus.write_byte(address, block)
            log.info(f"Set fan speed to {block}.")
        except IOError as e:
            temp = ""
            log.error("Cannot set fan speed.", exc_info=True)
        time.sleep(check_interval)


try:
    t1 = Thread(target=button_check)
    t2 = Thread(target=temp_check)
    t1.start()
    t2.start()
except:
    t1.stop()
    t2.stop()
    # GPIO.cleanup()

EOM
    chmod 755 "${powerbuttonscript}"

    # Stop the service if it is already present.
    if [[ -f "${daemonfanservice}" ]]; then
        systemctl stop ${daemonname}.service
    fi

    cat <<"EOM" >"${daemonfanservice}"
[Unit]
Description=Argon One Fan and Button Service
After=multi-user.target
[Service]
Type=simple
Restart=always
RemainAfterExit=true
ExecStart=/usr/local/bin/argononed
[Install]
WantedBy=multi-user.target
EOM
    chmod 644 "${daemonfanservice}"

    systemctl daemon-reload
    systemctl enable ${daemonname}.service
    systemctl start ${daemonname}.service
}

function uninstall_argonone() {
    rm -f ${powerbuttonscript}
    rm -f ${shutdownscript}
    systemctl stop ${daemonname}.service
    systemctl disable ${daemonname}.service
    rm -f ${daemonfanservice}
    systemctl daemon-reload
    rm -f ${daemonconfigfile}
    echo "Removed Argon One Services."
    echo "Cleanup will complete after restarting the device."
}

# Check number of command line arguments
if [[ $# -lt 1 ]]; then
    usage >&2
    exit 1
elif [[ $# -gt 1 ]]; then
    echo "[!] ERROR: Too many arguments."
    usage >&2
    exit 1
fi

# Check if the user running the script is root
if [[ "$(id -u)" -ne 0 ]]; then
    echo "[!] ERROR: You need to be root."
    exit 1
fi

if [[ "${HOSTTYPE}" != "arm" ]] && [[ "${HOSTTYPE}" != "aarch64" ]]; then
    echo "[!] ERROR: This script is only intended to run on ARM devices."
    exit 1
fi

# Check if we're running on a Raspberry Pi
if [[ -e /proc/device-tree/model ]]; then
    read -r -d $'\0' PI_MODEL </proc/device-tree/model
fi
if [[ ! "${PI_MODEL:-}" =~ ^Raspberry.Pi.*$ ]]; then
    echo "[!] ERROR: This is not a Raspberry Pi."
    exit 1
fi

# Check if we're running Ubuntu
IS_UBUNTU=$(lsb_release -is)
if [[ "${IS_UBUNTU}" != "Ubuntu" ]]; then
    echo "[!] ERROR: This script is only intended to run on Ubuntu."
    exit 1
fi

daemonname="argononed"
powerbuttonscript="/usr/local/bin/${daemonname}"
shutdownscript="/lib/systemd/system-shutdown/${daemonname}-poweroff"
daemonconfigfile="/etc/${daemonname}.conf"
daemonfanservice="/lib/systemd/system/${daemonname}.service"

# Parse command line arguments
case "${1}" in
    -c | --config)
        config_argonone
        exit 0
        ;;
    -i | --install)
        install_argonone
        exit 0
        ;;
    -u | --uninstall)
        uninstall_argonone
        exit 0
        ;;
    -h | --help)
        usage
        exit 0
        ;;
    *)
        echo "[!] ERROR: \"${1}\" is not a supported parameter." >&2
        usage >@2
        exit 1
        ;;
esac
